# Разработчик плагина Soldi_n
# Список мобов, которых нельзя добавлять в спавнер
blocked-mobs:
  - CREEPER
  - VILLAGER
  - ENDER_DRAGON

# Сообщение игроку
deny-message: "§cНельзя сувать моба в спавнер!"

# Логировать действия в консоль
log-actions: true
